# Generated by Django 4.2.11 on 2024-03-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_chathistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='name',
            field=models.CharField(default='Chat', max_length=200),
        ),
    ]
