# Generated by Django 4.2.11 on 2024-03-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0005_questionaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chathistory',
            old_name='answers',
            new_name='response',
        ),
        migrations.RemoveField(
            model_name='chathistory',
            name='questions',
        ),
        migrations.AlterField(
            model_name='questionaire',
            name='questionaire',
            field=models.FileField(upload_to='questionaires/'),
        ),
    ]
