# Generated by Django 4.2.11 on 2024-03-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0006_rename_answers_chathistory_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='reportYear',
            field=models.CharField(default='2020', max_length=5),
        ),
    ]
