# Generated by Django 4.2.11 on 2024-03-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0007_document_reportyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionaire',
            name='reportYear',
            field=models.CharField(default='2020', max_length=5),
        ),
    ]
